name: 'gopxl docs'
author: 'Mark Kremer'
description: 'A static website generator for the gopxl Markdown documentation'
inputs:
  docs-directory:
    description: 'Path to the documentation directory inside the repository'
    required: false
    default: 'docs'
  destination-directory:
    description: 'Directory the generated files will be stored to'
    required: false
    default: '_site/'
  deploy-url:
    description: "URL the site will be deployed to (https://owner.github.com/project)"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-url"
    - ${{ inputs.deploy-url }}
    - "-repository-url"
    - "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY"
    - "-repository"
    - "./"
    - "-docs"
    - ${{ inputs.docs-directory }}
    - "-dest"
    - ${{ inputs.destination-directory }}
