# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:

  upload-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    env:
      DOCS_DIR: 'docs/'
      DEST_DIR: '_site/'
    steps:
      - uses: actions/configure-pages@v5
        id: configure-pages
      - uses: actions/checkout@v3
      - uses: ./
        with:
          deploy-url: ${{ steps.configure-pages.outputs.base_url }}
          repository-url: https://github.com/$GITHUB_REPOSITORY_OWNER/$GITHUB_REPOSITORY
          docs-directory: ${{ env.DOCS_DIR }}
          destination-directory: ${{ env.DEST_DIR }}
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DEST_DIR }}
      - uses: actions/deploy-pages@v4
